# Generated by Django 4.2.6 on 2024-05-02 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('duracion_real', models.DurationField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.actividad')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.calendario')),
            ],
        ),
    ]
